#!/usr/bin/python
# -*- coding: utf-8 -*-·

# Copyright © 2006 TUBITAK/UEKAE
# Licensed under the GNU General Public License, version 2.
# See the file http://www.gnu.org/copyleft/gpl.txt.
#
# S.Çağlar Onur <caglar@pardus.org.tr>

import os
import re
import sys

if not os.path.exists("/boot/grub/grub.conf"):
    # if there is no grub.conf then exit silently
    sys.exit()

# Determine latest kernel
kernel = os.readlink("/boot/latestkernel").split("kernel-")[1]
initramfs = os.readlink("/boot/latestinitramfs").split("initramfs-")[1]

# Read /etc/pardus-release for title
f = open("/etc/pardus-release", "r")
release = f.readline()
f.close()

# Read entire grub.conf
f = open("/boot/grub/grub.conf", "r")
lines = f.readlines()
f.close()

header = ""
container = []
section = []
for l in lines:
    l = l.strip()
    # ignore emtpy lines or comments
    if len(l) == 0 or l.startswith("#"):
        continue
    if l.startswith("title"):
        if len(section) > 0:
            container.append(section)
        section = [l]
        continue
    if len(section) > 0:
        section.append(l)
        continue
    else:
        header += "%s\n" % l
container.append(section)

f = open("/boot/grub/grub.conf", "w")
f.write(header)

f.write("\n")
for l in container[0]:
    if l.startswith("title"):
        f.write("title %s [%s]\n" % (release.strip("\n"), kernel))
    elif l.startswith("kernel"):
        f.write(re.sub("(.*)(kernel-.*)(root=.*)", r"\1kernel-%s \3\n" % kernel, l))
    elif l.startswith("initrd"):
       f.write(re.sub("(.*)((initrd|initramfs)-.*)", r"\1initramfs-%s\n" % initramfs, l))
    else:
        f.write("%s\n" % l)
f.write("\n")

for list in container:
    for line in list:
        f.write("%s\n" % line)
    f.write("\n")
f.close()
